CC     = gcc
OBJS   = my_c.o
# -W* for warnings, -g3 for maximum debug, -O3 for maximum optimization
CFLAGS = -Wall -Wextra -Wundef -Wshadow -Wpointer-arith -Wcast-align -Wstrict-prototypes -Waggregate-return \
         -Wcast-qual -Wswitch-default -Wswitch-enum -Wconversion -Wunreachable-code -Wfloat-equal -g3 -O3  #-Wwrite-strings

all: head tail findlocationfast

head: $(OBJS) head.o
	$(CC) $(CFLAGS) -o $@ $^

tail: $(OBJS) linked_list.o tail.o
	$(CC) $(CFLAGS) -o $@ $^

findlocationfast: $(OBJS) findlocationfast.o
	$(CC) $(CFLAGS) -o $@ $^

# deletes files generated by compilation
clean:
	rm -f *.o head tail findlocationfast

run-h: head
	./head

run-t: tail
	./tail

run-f: findlocationfast
	./findlocationfast

my_c.o: my_c.c
linked_list.o: linked_list.c linked_list.h my_c.h
head.o: head.c my_c.h
tail.o: tail.c my_c.h linked_list.h
findlocationfast.o: findlocationfast.c my_c.h

